version: '2'

services:

  nginx:
    image: jwilder/nginx-proxy
    container_name: unxsbind-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true

  certbot:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: unxsbind-certbot
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html

  mysql:
    image: unxsio/unxsbind-mysql
    container_name: unxsbind-mysql
    volumes:
      - /var/lib/mysql/$EXTERNAL_HOSTNAME:/var/lib/mysql

  unxsbind:
    image: unxsio/unxsbind
    container_name: unxsbind
    hostname: $EXTERNAL_HOSTNAME
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    links:
      - mysql:unxsbind-mysql
    expose:
      - 8088
    environment:
      - VIRTUAL_HOST=$EXTERNAL_HOSTNAME
      - LETSENCRYPT_HOST=$EXTERNAL_HOSTNAME
      - LETSENCRYPT_EMAIL=certbot@unxs.io

  webhook:
    image: unxsio/unxsbind
    container_name: unxsbind
    hostname: $EXTERNAL_WEBHOOK_HOSTNAME
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /usr/bin/docker
    expose:
      - 8088
    environment:
      - VIRTUAL_HOST=$EXTERNAL_WEBHOOK_HOSTNAME
      - LETSENCRYPT_HOST=$EXTERNAL_WEBHOOK_HOSTNAME
      - LETSENCRYPT_EMAIL=certbot@unxs.io
